import Head from "next/head";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Vendo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" type="text/css" />
      </Head>
      <main>{children}</main>
    </>
  );
}
